
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mech
 */
public class currencyconverter extends javax.swing.JFrame {

    /**
     * Creates new form currencyconverter
     */
    public currencyconverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        from = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        to = new javax.swing.JComboBox<>();
        convert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Currency Converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 80);

        text.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        getContentPane().add(text);
        text.setBounds(280, 150, 140, 25);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel2.setText("AMOUNT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 220, 25);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel3.setText("FROM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 260, 150, 25);

        from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "AMERICA", "ENGLAND", "CHINESE YUAN(CNY)", "JAPANESE YEN", " " }));
        getContentPane().add(from);
        from.setBounds(280, 260, 140, 27);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel4.setText("TO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 350, 80, 25);

        to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "AMERICA", "ENGLAND", "CHINESE YUAN(CNY)", "JAPANESE YEN" }));
        getContentPane().add(to);
        to.setBounds(280, 350, 140, 27);

        convert.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        getContentPane().add(convert);
        convert.setBounds(90, 460, 280, 37);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 540, 210, 31);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mech\\Desktop\\IMG_20230926_150741.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 80, 430, 570);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mech\\Desktop\\istockphoto-472317739-612x612_2.jpg")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mech\\Desktop\\Flag-United-States-of-America_1.jpg")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mech\\Desktop\\iStock-1445012622-1024x576_1_1.jpg")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mech\\Desktop\\IMG_20230926_155310_1_1.jpg")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mech\\Desktop\\IMG_20230926_155310_1_1.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(430, 0, 320, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
            double num1;
            double result;
    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        text.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        num1=Double.parseDouble(text.getText());
        if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="AMERICA"){
        result=num1*83;
        JOptionPane.showMessageDialog(null,"CURRENCY (RUPPEES <===> DOLLARS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="ENGLAND"){
        result=num1*0.82;
                JOptionPane.showMessageDialog(null,"CURRENCY (DOLLARS <===> POUNDS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="ENGLAND"){
        result=num1*0.0099;
                JOptionPane.showMessageDialog(null,"CURRENCY (RUPPEES <===> POUNDS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="CHINESE YUAN(CNY)"&&to.getSelectedItem().toString()=="ENGLAND"){
        result=num1*0.11;
                JOptionPane.showMessageDialog(null,"CURRENCY (YUAN(CNY) <===> POUNDS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="JAPANESE YEN"){
        result=num1*149.02;
                JOptionPane.showMessageDialog(null,"CURRENCY (DOLLARS <===> YEN) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="CHINESE YUAN(CNY)"){
        result=num1*0.088;
                JOptionPane.showMessageDialog(null,"CURRENCY (RUPPEES <===> YUAN(CNY)) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="INDIA"&&to.getSelectedItem().toString()=="JAPANESE YEN"){
        result=num1*0.65;
                JOptionPane.showMessageDialog(null,"CURRENCY (RUPPEES <===> YEN) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="CHINESE YUAN(CNY)"){
        result=num1*7.30;
                JOptionPane.showMessageDialog(null,"CURRENCY (DOLLARS <===> YUAN(CNY)) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="JAPANESE YEN"){
        result=num1*181.00;
                JOptionPane.showMessageDialog(null,"CURRENCY (POUNDS <===> YEN) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="CHINESE YUAN(CNY)"&&to.getSelectedItem().toString()=="AMERICA"){
        result=num1*0.14;
                JOptionPane.showMessageDialog(null,"CURRENCY (YUAN(CNY) <===> DOLLARS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="CHINESE YUAN(CNY)"&&to.getSelectedItem().toString()=="INDIA"){
        result=num1*11.48;
                JOptionPane.showMessageDialog(null,"CURRENCY (YUAN(CNY) <===> RUPPEES) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="CHINESE YUAN(CNY)"&&to.getSelectedItem().toString()=="JAPANESE YEN"){
        result=num1*20.40;
                JOptionPane.showMessageDialog(null,"CURRENCY (YUAN(CNY) <===> YEN) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="AMERICA"&&to.getSelectedItem().toString()=="INDIA"){
        result=num1*83.21;
                JOptionPane.showMessageDialog(null,"CURRENCY (DOLLARS <===> RUPPEES) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="INDIA"){
        result=num1*101.06;
                JOptionPane.showMessageDialog(null,"CURRENCY (POUNDS <===> RUPPEES) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="CHINESE YUAN(CNY)"){
        result=num1*8.87;
                JOptionPane.showMessageDialog(null,"CURRENCY (POUNDS <===> YUAN(CNY)) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="ENGLAND"&&to.getSelectedItem().toString()=="AMERICA"){
        result=num1*1.21;
                JOptionPane.showMessageDialog(null,"CURRENCY (POUNDS <===> DOLLERS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="JAPANESE YEN"&&to.getSelectedItem().toString()=="INDIA"){
        result=num1*0.56;
                JOptionPane.showMessageDialog(null,"CURRENCY (YEN <===> RUPPEES) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="JAPANESE YEN"&&to.getSelectedItem().toString()=="AMERICA"){
        result=num1*0.0067;
                JOptionPane.showMessageDialog(null,"CURRENCY (YEN <===> DOLLARS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="JAPANESE YEN"&&to.getSelectedItem().toString()=="ENGLAND"){
        result=num1*0.0055;
                JOptionPane.showMessageDialog(null,"CURRENCY (YEN <===> POUNDS) SUCCESSFULLY CONVERTED");}
        else if(from.getSelectedItem().toString()=="JAPANESE YEN"&&to.getSelectedItem().toString()=="CHINESE YUAN(CNY)"){
        result=num1*0.049;
                JOptionPane.showMessageDialog(null,"CURRENCY (YEN <===> YUAN(CNY)) SUCCESSFULLY CONVERTED");}
        else
        result=num1*100;

        text.setText(result+"");
    }//GEN-LAST:event_convertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currencyconverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JComboBox<String> from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField text;
    private javax.swing.JComboBox<String> to;
    // End of variables declaration//GEN-END:variables
}
